//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.27 at 08:07:27 PM EDT 
//


package edu.wsu.MechTurk.QuestionFormAnswer;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Answer" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="QuestionIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;choice>
 *                     &lt;sequence>
 *                       &lt;element name="SelectionIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                       &lt;element name="OtherSelectionText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                     &lt;/sequence>
 *                     &lt;element name="FreeText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;sequence>
 *                       &lt;element name="UploadedFileSizeInBytes" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                       &lt;element name="UploadedFileKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;/sequence>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "answer"
})
@XmlRootElement(name = "QuestionFormAnswers")
public class QuestionFormAnswers {

    @XmlElement(name = "Answer", required = true)
    protected List<QuestionFormAnswers.Answer> answer;

    /**
     * Gets the value of the answer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the answer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnswer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QuestionFormAnswers.Answer }
     * 
     * 
     */
    public List<QuestionFormAnswers.Answer> getAnswer() {
        if (answer == null) {
            answer = new ArrayList<QuestionFormAnswers.Answer>();
        }
        return this.answer;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="QuestionIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;choice>
     *           &lt;sequence>
     *             &lt;element name="SelectionIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *             &lt;element name="OtherSelectionText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *           &lt;/sequence>
     *           &lt;element name="FreeText" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *           &lt;sequence>
     *             &lt;element name="UploadedFileSizeInBytes" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *             &lt;element name="UploadedFileKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *           &lt;/sequence>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "questionIdentifier",
        "selectionIdentifier",
        "otherSelectionText",
        "freeText",
        "uploadedFileSizeInBytes",
        "uploadedFileKey"
    })
    public static class Answer {

        @XmlElement(name = "QuestionIdentifier", required = true)
        protected String questionIdentifier;
        @XmlElement(name = "SelectionIdentifier")
        protected List<String> selectionIdentifier;
        @XmlElement(name = "OtherSelectionText")
        protected String otherSelectionText;
        @XmlElement(name = "FreeText")
        protected String freeText;
        @XmlElement(name = "UploadedFileSizeInBytes")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger uploadedFileSizeInBytes;
        @XmlElement(name = "UploadedFileKey")
        protected String uploadedFileKey;

        /**
         * Gets the value of the questionIdentifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQuestionIdentifier() {
            return questionIdentifier;
        }

        /**
         * Sets the value of the questionIdentifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQuestionIdentifier(String value) {
            this.questionIdentifier = value;
        }

        /**
         * Gets the value of the selectionIdentifier property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the selectionIdentifier property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSelectionIdentifier().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getSelectionIdentifier() {
            if (selectionIdentifier == null) {
                selectionIdentifier = new ArrayList<String>();
            }
            return this.selectionIdentifier;
        }

        /**
         * Gets the value of the otherSelectionText property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOtherSelectionText() {
            return otherSelectionText;
        }

        /**
         * Sets the value of the otherSelectionText property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOtherSelectionText(String value) {
            this.otherSelectionText = value;
        }

        /**
         * Gets the value of the freeText property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFreeText() {
            return freeText;
        }

        /**
         * Sets the value of the freeText property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFreeText(String value) {
            this.freeText = value;
        }

        /**
         * Gets the value of the uploadedFileSizeInBytes property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getUploadedFileSizeInBytes() {
            return uploadedFileSizeInBytes;
        }

        /**
         * Sets the value of the uploadedFileSizeInBytes property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setUploadedFileSizeInBytes(BigInteger value) {
            this.uploadedFileSizeInBytes = value;
        }

        /**
         * Gets the value of the uploadedFileKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUploadedFileKey() {
            return uploadedFileKey;
        }

        /**
         * Sets the value of the uploadedFileKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUploadedFileKey(String value) {
            this.uploadedFileKey = value;
        }

    }

}
